def draw_tree():


    print("                                / \ ")
    print("                               /   \ ")
    print("                              /     \ ")
    print("                           ---       --- ")
    print("                          /             \ ")
    print("                         /               \ ")
    print("                        /                 \ ")
    print("                     ---                   --- ")
    print("                    /                         \ ")
    print("                   /                           \ ")
    print("                  /                             \ ")
    print("               ---                               --- ")
    print("              /                                     \ ")
    print("             /                                       \ ")
    print("            /                                         \ ")
    print("         ---                                           --- ")
    print("        /                                                 \ ")
    print("       /                                                   \ ")
    print("      /                                                     \ ")
    print("   ---                                                       --- ")
    print("  /                                                             \ ")
    print(" /                                                               \ ")
    print("/                                                                 \ ")
    print("___________________________________________________________________")
    print("                 |                            |")
    print("                 |                            |")
    print("                 |                            |")
    print("                 |                            |")
    print("                 |                            |")
    print("                 |                            |")
    print("                 |                            |")
    print("                 |                            |")
    print("                 |                            |")
    print("                 |                            |")

    return
