def draw_tree():

    print("                              /\ ")
    print("                             /  \ ")
    print("                            /    \ ")
    print("                           /      \ ")
    print("                          /        \ ")
    print("                         /          \ ")
    print("                        /            \ ")
    print("                     ---              --- ")
    print("                    /                    \ ")
    print("                   /                      \ ")
    print("                  /                        \ ")
    print("               ---                          --- ")
    print("              /                                \ ")
    print("             /                                  \ ")
    print("            /                                    \ ")
    print("         ---                                      --- ")
    print("        /                                            \ ")
    print("       /                                              \ ")
    print("      /                                                \ ")
    print("   ---                                                  --- ")
    print("  /                                                        \ ")
    print(" /                                                          \ ")
    print("/                                                            \ ")
    print("_____________________________________________________________")
    print("                 |                       |")
    print("                 |                       |")
    print("                 |                       |")
    print("                 |                       |")
    print("                 |                       |")
    print("                 |                       |")
    print("                 |                       |")
    print("                 |                       |")


    return
